### ISSUE TITLE
kintone側の設定フィルター項目について

### ISSUE THREAD

**Issue by paper29squad** [uchan-nos/rust-wasm-kintone#1]
README.md

filters | チェックボックス | 項目：resize, rtate, grayscale, huerotate, blur, brighten
-- | -- | --

とありますが、項目名`rtate`は正しいでしょうか？

rust-wasm-kintone/src/main.rs
`            "rotate" => match filter_params.rotate_angle {`
では、`rotate`を期待しているように思えます。

**Comment by uchan-nos** [comment]
そうですね。単なる打ち間違いだと思います。

**Comment by paper29squad** [comment]
ありがとうございます。
